---
version: 1.0.0
slug: emporia
name: Emporia Vue
description: Emporia Vue devices integration
url: https://github.com/alex-savin/hassio-addons-test/tree/master/emporia
# codenotary: notary@home-assistant.io
#image: ghcr.io/alex-savin/addon-emporia
arch:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64
auth_api: false
image: smarthouseint/addon-emporia
map:
  - config:rw
  - share
options:
  mqtt:
    host: 127.0.0.1
    port: 1883
    username: username
    password: password
    clientid: emporia
    retained: true
    topic: emporia
  credentials:
    username:
    password:
    access_token:
    id_token:
    refresh_token:
    token_expiration:
  emporia:
    client_id: 4qte47jbstod8apnfic0bunmrq
    region: us-east-2
    user_pool: us-east-2_ghlOXVLi1
  settings:
    scope_of_interest:
      - minute
      - day
      - month
  timezone: America/New_York
  logLevel: debug
  shareDeidentifiedData: true
schema:
  mqtt:
    host: str
    port: port
    username: str?
    password: password?
    clientid: str
    retained: bool
    topic: str
  credentials:
    username: str
    password: password
    access_token: str?
    id_token: str?
    refresh_token: str?
    token_expiration: int?
  emporia:
    client_id: str
    region: str
    user_pool: str
  settings:
    scope_of_interest:
      - str
  timezone: str
  logLevel: match(^(trace|debug|info|notice|warning|error|fatal)$)?
  shareDeidentifiedData: bool
services:
  - mqtt:want
startup: system
#watchdog: tcp://[HOST]:1883
init: false
